# ===== ENVIRONMENT =====
num_seconds: 1000
delta_time: 5

# ===== RL HYPERPARAMETERS =====
gamma: 0.9
episodes: 10
policy_update_interval: 2

# ===== EPSILON =====
epsilon:
  start: 0.1
  min: 0.01
  decay: 0.995

# ===== TRAINING =====
seeds:
  - 24
  - 61
  - 77
  - 34

# ===== MONTE CARLO =====
monte_carlo:
  method: "every_visit"
